# Generated by Django 5.2.7 on 2025-11-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(db_column='id_lugar', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=200, null=True)),
                ('area', models.CharField(blank=True, db_column='area', max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='ciudad', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, db_column='fecha_eliminacion', null=True)),
                ('creado_por', models.CharField(blank=True, db_column='creado_por', max_length=50, null=True)),
                ('modificado_por', models.CharField(blank=True, db_column='modificado_por', max_length=50, null=True)),
                ('eliminado_por', models.CharField(blank=True, db_column='eliminado_por', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Lugar',
            },
        ),
    ]
