# Generated by Django 5.2.7 on 2025-11-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscustomuser',
            name='firma',
            field=models.ImageField(blank=True, db_column='firma', null=True, upload_to='firmas/'),
        ),
    ]
