# Generated by Django 5.2.7 on 2025-11-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userscustomuser_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscustomuser',
            name='codigo',
            field=models.CharField(blank=True, db_column='codigo', max_length=50, null=True),
        ),
    ]
