# Generated by Django 5.2.7 on 2026-01-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0012_remove_garantia_foto_factura_and_more'),
        ('users', '0003_userscustomuser_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscustomuser',
            name='id_equipo',
            field=models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='equipo.equipo'),
        ),
    ]
