# Generated by Django 5.2.7 on 2025-11-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(db_column='id_componente', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=50)),
                ('aec', models.CharField(db_column='aec', max_length=50)),
                ('marca', models.CharField(blank=True, db_column='marca', max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, db_column='modelo', max_length=50, null=True)),
                ('serial', models.CharField(db_column='serial', max_length=50, unique=True)),
                ('estado', models.CharField(db_column='estado', default='Activo', max_length=20)),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=300, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, db_column='fecha_eliminacion', null=True)),
                ('creado_por', models.CharField(blank=True, db_column='creado_por', max_length=50, null=True)),
                ('modificado_por', models.CharField(blank=True, db_column='modificado_por', max_length=50, null=True)),
                ('eliminado_por', models.CharField(blank=True, db_column='eliminado_por', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Componente',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(db_column='id_equipo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=50)),
                ('aec', models.CharField(db_column='aec', max_length=50)),
                ('marca', models.CharField(blank=True, db_column='marca', max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, db_column='modelo', max_length=50, null=True)),
                ('so', models.CharField(blank=True, db_column='so', max_length=50, null=True)),
                ('procesador', models.CharField(blank=True, db_column='procesador', max_length=50, null=True)),
                ('tipo_ram', models.CharField(blank=True, db_column='tipo_ram', max_length=50, null=True)),
                ('ram', models.CharField(blank=True, db_column='ram', max_length=50, null=True)),
                ('tipo_disco', models.CharField(blank=True, db_column='tipo_disco', max_length=50, null=True)),
                ('disco', models.CharField(blank=True, db_column='disco', max_length=50, null=True)),
                ('estado', models.CharField(db_column='estado', default='Activo', max_length=20)),
                ('estado_disco', models.CharField(blank=True, db_column='estado_disco', max_length=50, null=True)),
                ('serial', models.CharField(db_column='serial', max_length=50, unique=True)),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=300, null=True)),
                ('ip', models.CharField(blank=True, db_column='ip', max_length=45, null=True)),
                ('ip_maquina', models.CharField(blank=True, db_column='ip_maquina', max_length=45, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, db_column='fecha_eliminacion', null=True)),
                ('creado_por', models.CharField(blank=True, db_column='creado_por', max_length=50, null=True)),
                ('modificado_por', models.CharField(blank=True, db_column='modificado_por', max_length=50, null=True)),
                ('eliminado_por', models.CharField(blank=True, db_column='eliminado_por', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Equipo',
            },
        ),
    ]
