# Generated by Django 5.2.7 on 2025-11-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='estado',
        ),
    ]
