# Generated by Django 5.2.7 on 2025-11-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_remove_equipo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado_equipo',
            field=models.CharField(blank=True, db_column='estado_equipo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado_disco',
            field=models.CharField(blank=True, db_column='estado_disco', max_length=300, null=True),
        ),
    ]
