# Generated by Django 5.2.7 on 2025-11-12 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0004_equipo_estado_equipo_alter_equipo_estado_disco'),
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='id_lugar',
            field=models.ForeignKey(blank=True, db_column='id_lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lugar.lugar'),
        ),
    ]
