# Generated by Django 5.2.7 on 2025-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0005_componente_id_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado_equipo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'Mantenimiento'), ('INACTIVO', 'Inactivo')], db_column='estado_equipo', default='ACTIVO', max_length=50),
        ),
    ]
