# Generated by Django 5.2.7 on 2026-01-22 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0006_alter_equipo_estado_equipo'),
        ('lugar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'Marca',
            },
        ),
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='so',
        ),
        migrations.AddField(
            model_name='equipo',
            name='sistema_operativo',
            field=models.CharField(blank=True, db_column='sistema_operativo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='componente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='estado', default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='componente',
            name='id_equipo',
            field=models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='equipo.equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_lugar',
            field=models.ForeignKey(blank=True, db_column='id_lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='lugar.lugar'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_users',
            field=models.ForeignKey(blank=True, db_column='id_users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_column='ip', null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='marca_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes', to='equipo.marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='equipo.marca'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['serial'], name='Equipo_serial_a50d18_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['estado_equipo'], name='Equipo_estado__198123_idx'),
        ),
    ]
