# Generated by Django 5.2.7 on 2026-01-24 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0007_marca_alter_componente_options_alter_equipo_options_and_more'),
        ('lugar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='ip_maquina',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='marca_ref',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_lugar',
            field=models.ForeignKey(blank=True, db_column='id_lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lugar', to='lugar.lugar'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_users',
            field=models.ForeignKey(blank=True, db_column='id_users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id_disco', models.AutoField(db_column='id_disco', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discos', to='equipo.equipo')),
            ],
            options={
                'db_table': 'Disco',
                'ordering': ['-id_disco'],
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id_ram', models.AutoField(db_column='id_ram', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('frecuencia', models.IntegerField(blank=True, null=True)),
                ('voltaje', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rams', to='equipo.equipo')),
            ],
            options={
                'db_table': 'Ram',
                'ordering': ['-id_ram'],
            },
        ),
    ]
