# Generated by Django 5.2.7 on 2026-01-24 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0008_remove_equipo_ip_maquina_remove_equipo_marca_ref_and_more'),
        ('lugar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='disco',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='estado_disco',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='tipo_disco',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='tipo_ram',
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_ref', to='equipo.marca'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='id_lugar',
            field=models.ForeignKey(blank=True, db_column='id_lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes', to='lugar.lugar'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='id_users',
            field=models.ForeignKey(blank=True, db_column='id_users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_lugar',
            field=models.ForeignKey(blank=True, db_column='id_lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='lugar.lugar'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_users',
            field=models.ForeignKey(blank=True, db_column='id_users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
