# Generated by Django 5.2.7 on 2026-01-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0010_remove_equipo_marca_ref_alter_componente_id_lugar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, db_column='fecha_eliminacion', null=True)),
                ('creado_por', models.CharField(blank=True, db_column='creado_por', max_length=50, null=True)),
                ('modificado_por', models.CharField(blank=True, db_column='modificado_por', max_length=50, null=True)),
                ('eliminado_por', models.CharField(blank=True, db_column='eliminado_por', max_length=50, null=True)),
                ('id_garantia', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=150)),
                ('contacto_soporte', models.TextField(blank=True, help_text='Teléfonos, correos o links', null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de garantía')),
                ('duracion_meses', models.PositiveIntegerField(blank=True, default=12, null=True, verbose_name='Duración en meses')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin de garantía')),
                ('documento_pdf', models.FileField(blank=True, db_column='documento_pdf', help_text='Cargar el certificado de garantía en PDF', null=True, upload_to='garantias/documentos/')),
                ('foto_factura', models.ImageField(blank=True, db_column='foto_factura', help_text='Imagen de la factura o ticket', null=True, upload_to='garantias/facturas/')),
                ('foto_activo', models.ImageField(blank=True, help_text='Foto del equipo o componente físico', null=True, upload_to='garantias/activos/')),
                ('componente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garantia_info', to='equipo.componente')),
                ('equipo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garantia_info', to='equipo.equipo')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'db_table': 'Garantia',
            },
        ),
    ]
