# Generated by Django 5.2.7 on 2026-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0011_garantia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantia',
            name='foto_factura',
        ),
        migrations.AlterField(
            model_name='garantia',
            name='documento_pdf',
            field=models.FileField(blank=True, db_column='documento_pdf', help_text='Cargar el certificado de garantía en PDF', null=True, upload_to='documentos/garantias/'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='foto_activo',
            field=models.ImageField(blank=True, help_text='Foto del equipo o componente físico', null=True, upload_to='fotos/activos/'),
        ),
    ]
