# Generated by Django 5.2.7 on 2026-01-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0012_remove_garantia_foto_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento')], db_column='estado', default='ACTIVO', max_length=20),
        ),
    ]
