# Generated by Django 5.2.7 on 2025-11-04 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMantenimiento',
            fields=[
                ('id_reporte', models.AutoField(db_column='id_reporte', primary_key=True, serialize=False)),
                ('fecha_mantenimiento', models.DateTimeField(blank=True, db_column='fecha_mantenimiento', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=300, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=300, null=True)),
                ('firma_tecnico', models.CharField(blank=True, db_column='firma_tecnico', max_length=100, null=True)),
                ('firma_responsable', models.CharField(blank=True, db_column='firma_responsable', max_length=100, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, db_column='fecha_envio', null=True)),
                ('fecha_aprobacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, db_column='fecha_eliminacion', null=True)),
                ('creado_por', models.CharField(blank=True, db_column='creado_por', max_length=50, null=True)),
                ('modificado_por', models.CharField(blank=True, db_column='modificado_por', max_length=50, null=True)),
                ('eliminado_por', models.CharField(blank=True, db_column='eliminado_por', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Reporte_Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(db_column='id_ticket', primary_key=True, serialize=False)),
                ('fecha_inicio_t', models.DateTimeField(blank=True, db_column='fecha_inicio_t', null=True)),
                ('fecha_fin_t', models.DateTimeField(blank=True, db_column='fecha_fin_t', null=True)),
                ('estado_ticket', models.CharField(db_column='estado_ticket', default='Pendiente', max_length=20)),
                ('motivo_cancelacion', models.CharField(blank=True, db_column='motivo_cancelacion', max_length=300, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, db_column='fecha_cancelacion', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, db_column='fecha_eliminacion', null=True)),
                ('creado_por', models.CharField(blank=True, db_column='creado_por', max_length=50, null=True)),
                ('modificado_por', models.CharField(blank=True, db_column='modificado_por', max_length=50, null=True)),
                ('eliminado_por', models.CharField(blank=True, db_column='eliminado_por', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=300, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, db_column='fecha_modificacion')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, db_column='fecha_eliminacion', null=True)),
                ('creado_por', models.CharField(blank=True, db_column='creado_por', max_length=50, null=True)),
                ('modificado_por', models.CharField(blank=True, db_column='modificado_por', max_length=50, null=True)),
                ('eliminado_por', models.CharField(blank=True, db_column='eliminado_por', max_length=50, null=True)),
                ('id_equipo', models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipo.equipo')),
                ('id_lugar', models.ForeignKey(blank=True, db_column='id_lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lugar.lugar')),
            ],
            options={
                'db_table': 'Notificacion',
            },
        ),
    ]
