# Generated by Django 5.2.7 on 2025-11-04 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0002_initial'),
        ('lugar', '0001_initial'),
        ('mantenimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='id_users',
            field=models.ForeignKey(blank=True, db_column='id_users', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportemantenimiento',
            name='id_aprobado_por',
            field=models.ForeignKey(blank=True, db_column='id_aprobado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportemantenimiento',
            name='id_elaborado_por',
            field=models.ForeignKey(blank=True, db_column='id_elaborado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elaborados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportemantenimiento',
            name='id_equipo',
            field=models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipo.equipo'),
        ),
        migrations.AddField(
            model_name='reportemantenimiento',
            name='id_lugar',
            field=models.ForeignKey(blank=True, db_column='id_lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lugar.lugar'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_equipo',
            field=models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipo.equipo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_lugar',
            field=models.ForeignKey(blank=True, db_column='id_lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lugar.lugar'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_users',
            field=models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportemantenimiento',
            name='id_ticket',
            field=models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ticket'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='id_ticket',
            field=models.ForeignKey(blank=True, db_column='id_ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.ticket'),
        ),
    ]
