# Generated by Django 5.2.7 on 2025-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='insumos_detalle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_soporte',
            field=models.CharField(blank=True, choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('recarga_tinta', 'Recarga de Tinta'), ('tonner', 'Recarga de Tonner'), ('soporte_usuario', 'Soporte al Usuario')], max_length=50, null=True),
        ),
    ]
