# Generated by Django 5.2.7 on 2025-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_ticket_descripcion_ticket_insumos_detalle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='fecha_fin_t',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fecha_inicio_t',
        ),
        migrations.AddField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_column='prioridad', default='media', max_length=10),
        ),
    ]
