# Generated by Django 5.2.7 on 2025-12-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_remove_ticket_fecha_fin_t_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancelado_por',
            field=models.CharField(blank=True, choices=[('usuario', 'Cancelado por Usuario'), ('tecnico', 'Cancelado por Técnico')], db_column='cancelado_por', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado_ticket',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_column='estado_ticket', default='pendiente', max_length=20),
        ),
    ]
