# Generated by Django 5.2.7 on 2026-01-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_remove_ticket_creado_por_remove_ticket_eliminado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
