# Generated by Django 5.2.7 on 2026-01-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_ticket_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cancelado_por',
            field=models.CharField(blank=True, choices=[('usuario', 'Cancelado por Usuario'), ('tecnico', 'Cancelado por Técnico')], db_column='cancelado_por', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado_ticket',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_column='estado_ticket', default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_column='prioridad', default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo_soporte',
            field=models.CharField(blank=True, choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('recarga_tinta', 'Recarga de Tinta'), ('tonner', 'Recarga de Tonner'), ('soporte_usuario', 'Soporte al Usuario')], max_length=50, null=True),
        ),
    ]
