# Generated by Django 5.2.7 on 2026-01-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_alter_ticket_cancelado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado_ticket',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('documentando', 'Documentando'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_column='estado_ticket', default='pendiente', max_length=20),
        ),
    ]
