# Generated by Django 5.2.7 on 2026-01-16 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_alter_ticket_estado_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comentario_usuario',
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_tecnico_asignado',
            field=models.ForeignKey(blank=True, db_column='id_tecnico_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados_por_rol', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_users',
            field=models.ForeignKey(blank=True, db_column='id_users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados_por_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ComentarioTicket',
        ),
    ]
