# Generated by Django 5.2.7 on 2026-01-16 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_remove_ticket_comentario_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_tecnico_asignado',
            field=models.ForeignKey(blank=True, db_column='id_tecnico_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_ticket_asignado', to=settings.AUTH_USER_MODEL),
        ),
    ]
