# Generated by Django 5.2.7 on 2026-01-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0011_alter_ticket_id_tecnico_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
