# Generated by Django 5.2.7 on 2026-01-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0012_alter_ticket_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialticket',
            name='aprobado',
            field=models.IntegerField(choices=[(0, 'No aprobado'), (1, 'Aprobado')], db_column='aprobado', default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cancelado_por',
            field=models.CharField(blank=True, choices=[('usuario', 'Cancelado por Usuario'), ('tecnico', 'Cancelado por Técnico'), ('admin', 'Cancelado por Admin')], db_column='cancelado_por', max_length=20, null=True),
        ),
    ]
