# Generated by Django 5.2.7 on 2026-01-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0013_historialticket_aprobado_alter_ticket_cancelado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialticket',
            name='aprobado',
        ),
        migrations.AddField(
            model_name='ticket',
            name='aprobado',
            field=models.IntegerField(choices=[(0, 'No aprobado'), (1, 'Aprobado')], db_column='aprobado', default=0),
        ),
    ]
